<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>Limitless.Managed.TestScripts</AssemblyName>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="obj\**\*.cs;bin\**\*.cs" />
    <EmbeddedResource Remove="obj\**\*;bin\**\*" />
    <None Remove="obj\**\*;bin\**\*" />
  </ItemGroup>
  <ItemGroup Condition="'$(LimitlessManagedReferencePath)' != ''">
    <Reference Include="Limitless.Managed">
      <HintPath>$(LimitlessManagedReferencePath)</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup Condition="'$(LimitlessManagedReferencePath)' == ''">
    <ProjectReference Include="..\Limitless.Managed\Limitless.Managed.csproj" />
  </ItemGroup>
</Project>
