#include "PrecompiledHeader.h"
#include "Assets/GeneratedAssetRuntimeRegistry.h"

namespace Limitless::Assets
{
    GeneratedAssetRuntimeRegistry& GeneratedAssetRuntimeRegistry::GetInstance()
    {
        static GeneratedAssetRuntimeRegistry instance;
        return instance;
    }

    void GeneratedAssetRuntimeRegistry::Register(const std::string& key, Entry entry)
    {
        if (key.empty())
            return;

        std::unique_lock<std::shared_mutex> lock(m_Mutex);
        m_ByKey[key] = std::move(entry);
    }

    void GeneratedAssetRuntimeRegistry::RegisterAsset(const std::string& key,
                                                      const std::shared_ptr<Asset>& asset,
                                                      std::function<bool()> reload)
    {
        if (key.empty() || !asset)
            return;

        std::unique_lock<std::shared_mutex> lock(m_Mutex);
        auto& entry = m_ByKey[key];
        entry.AssetInstance = asset;
        if (reload)
            entry.Reload = std::move(reload);
    }

    void GeneratedAssetRuntimeRegistry::Unregister(const std::string& key)
    {
        if (key.empty())
            return;

        std::unique_lock<std::shared_mutex> lock(m_Mutex);
        m_ByKey.erase(key);
    }

    bool GeneratedAssetRuntimeRegistry::Has(const std::string& key) const
    {
        if (key.empty())
            return false;

        std::shared_lock<std::shared_mutex> lock(m_Mutex);
        return m_ByKey.find(key) != m_ByKey.end();
    }

    bool GeneratedAssetRuntimeRegistry::Reload(const std::string& key)
    {
        if (key.empty())
            return false;

        Entry entry = GetEntrySnapshot(key);
        if (entry.Reload)
            return entry.Reload();

        if (auto asset = entry.AssetInstance.lock())
            return asset->Reload();

        if (entry.AssetFactory)
        {
            auto created = entry.AssetFactory();
            if (!created)
                return false;

            {
                std::unique_lock<std::shared_mutex> lock(m_Mutex);
                if (auto it = m_ByKey.find(key); it != m_ByKey.end())
                    it->second.AssetInstance = created;
            }

            return created->Reload();
        }

        return false;
    }

    Result<std::string> GeneratedAssetRuntimeRegistry::LoadText(const std::string& key) const
    {
        if (key.empty())
            return Result<std::string>(ErrorCode::InvalidArgument, "Generated asset key is empty");

        Entry entry = GetEntrySnapshot(key);
        if (!entry.LoadText)
        {
            return Result<std::string>(
                ErrorCode::ResourceNotFound,
                "No generated text provider registered for '" + key + "'");
        }

        return entry.LoadText();
    }

    Result<std::vector<uint8_t>> GeneratedAssetRuntimeRegistry::LoadBytes(const std::string& key) const
    {
        if (key.empty())
            return Result<std::vector<uint8_t>>(ErrorCode::InvalidArgument, "Generated asset key is empty");

        Entry entry = GetEntrySnapshot(key);
        if (!entry.LoadBytes)
        {
            return Result<std::vector<uint8_t>>(
                ErrorCode::ResourceNotFound,
                "No generated byte provider registered for '" + key + "'");
        }

        return entry.LoadBytes();
    }

    GeneratedAssetRuntimeRegistry::Entry GeneratedAssetRuntimeRegistry::GetEntrySnapshot(const std::string& key) const
    {
        std::shared_lock<std::shared_mutex> lock(m_Mutex);
        if (auto it = m_ByKey.find(key); it != m_ByKey.end())
            return it->second;
        return {};
    }
}
