using Coral.Managed.Interop;

namespace Limitless.Managed;

internal static class ScriptBridge
{
#pragma warning disable 0649
    internal static unsafe delegate*<NativeString, void> LogInfoIcall;
    internal static unsafe delegate*<NativeString, void> LogWarningIcall;
    internal static unsafe delegate*<NativeString, void> LogErrorIcall;
    internal static unsafe delegate*<uint, void> SetRandomSeedIcall;
    internal static unsafe delegate*<int, int, int> RandomRangeIntIcall;
    internal static unsafe delegate*<float, float, float> RandomRangeFloatIcall;
    internal static unsafe delegate*<float> RandomValueIcall;
    internal static unsafe delegate*<NativeString, int, bool> LoadSceneIcall;
    internal static unsafe delegate*<bool> ReloadCurrentSceneIcall;
    internal static unsafe delegate*<NativeString, bool> SetActiveSceneIcall;
    internal static unsafe delegate*<NativeString, bool> UnloadSceneIcall;
    internal static unsafe delegate*<NativeString, uint> CreateEntityIcall;
    internal static unsafe delegate*<uint, bool> DestroyEntityIcall;
    internal static unsafe delegate*<uint, bool> EntityExistsIcall;
    internal static unsafe delegate*<uint, bool> GetEntityEnabledIcall;
    internal static unsafe delegate*<uint, bool, bool> SetEntityEnabledIcall;
    internal static unsafe delegate*<uint, bool> IsEntityEnabledInHierarchyIcall;
    internal static unsafe delegate*<uint, uint, bool> SetParentIcall;
    internal static unsafe delegate*<uint, uint> GetParentIcall;
    internal static unsafe delegate*<uint, uint> GetChildCountIcall;
    internal static unsafe delegate*<uint, uint, uint> GetChildAtIcall;
    internal static unsafe delegate*<NativeString, uint> FindEntityByTagIcall;
    internal static unsafe delegate*<uint, bool> HasTagComponentIcall;
    internal static unsafe delegate*<uint, NativeString> GetTagIcall;
    internal static unsafe delegate*<uint, NativeString, bool> SetTagIcall;
    internal static unsafe delegate*<uint, byte> GetEntityLayerIcall;
    internal static unsafe delegate*<uint, byte, void> SetEntityLayerIcall;
    internal static unsafe delegate*<uint, bool> HasTransformComponentIcall;
    internal static unsafe delegate*<uint, Vector3> GetTransformPositionIcall;
    internal static unsafe delegate*<uint, Vector3, void> SetTransformPositionIcall;
    internal static unsafe delegate*<uint, Vector3> GetTransformRotationIcall;
    internal static unsafe delegate*<uint, Vector3, void> SetTransformRotationIcall;
    internal static unsafe delegate*<uint, Vector3> GetTransformScaleIcall;
    internal static unsafe delegate*<uint, Vector3, void> SetTransformScaleIcall;
    internal static unsafe delegate*<uint, bool> HasCameraComponentIcall;
    internal static unsafe delegate*<uint, int> GetCameraProjectionIcall;
    internal static unsafe delegate*<uint, int, void> SetCameraProjectionIcall;
    internal static unsafe delegate*<uint, bool> GetCameraPrimaryIcall;
    internal static unsafe delegate*<uint, bool, void> SetCameraPrimaryIcall;
    internal static unsafe delegate*<uint, float> GetCameraZoomIcall;
    internal static unsafe delegate*<uint, float, void> SetCameraZoomIcall;
    internal static unsafe delegate*<uint, float> GetCameraNearPlaneIcall;
    internal static unsafe delegate*<uint, float, void> SetCameraNearPlaneIcall;
    internal static unsafe delegate*<uint, float> GetCameraFarPlaneIcall;
    internal static unsafe delegate*<uint, float, void> SetCameraFarPlaneIcall;
    internal static unsafe delegate*<uint, float> GetCameraFieldOfViewYDegreesIcall;
    internal static unsafe delegate*<uint, float, void> SetCameraFieldOfViewYDegreesIcall;
    internal static unsafe delegate*<uint, uint> GetCameraCullingMaskIcall;
    internal static unsafe delegate*<uint, uint, void> SetCameraCullingMaskIcall;
    internal static unsafe delegate*<uint, bool> HasBoxCollider2DComponentIcall;
    internal static unsafe delegate*<uint, Vector2> GetBoxCollider2DOffsetIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetBoxCollider2DOffsetIcall;
    internal static unsafe delegate*<uint, Vector2> GetBoxCollider2DSizeIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetBoxCollider2DSizeIcall;
    internal static unsafe delegate*<uint, float> GetBoxCollider2DDensityIcall;
    internal static unsafe delegate*<uint, float, void> SetBoxCollider2DDensityIcall;
    internal static unsafe delegate*<uint, float> GetBoxCollider2DFrictionIcall;
    internal static unsafe delegate*<uint, float, void> SetBoxCollider2DFrictionIcall;
    internal static unsafe delegate*<uint, float> GetBoxCollider2DRestitutionIcall;
    internal static unsafe delegate*<uint, float, void> SetBoxCollider2DRestitutionIcall;
    internal static unsafe delegate*<uint, bool> GetBoxCollider2DIsSensorIcall;
    internal static unsafe delegate*<uint, bool, void> SetBoxCollider2DIsSensorIcall;
    internal static unsafe delegate*<uint, ulong> GetBoxCollider2DCollisionLayerIcall;
    internal static unsafe delegate*<uint, ulong, void> SetBoxCollider2DCollisionLayerIcall;
    internal static unsafe delegate*<uint, ulong> GetBoxCollider2DCollisionMaskIcall;
    internal static unsafe delegate*<uint, ulong, void> SetBoxCollider2DCollisionMaskIcall;
    internal static unsafe delegate*<uint, bool> HasCircleCollider2DComponentIcall;
    internal static unsafe delegate*<uint, Vector2> GetCircleCollider2DOffsetIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetCircleCollider2DOffsetIcall;
    internal static unsafe delegate*<uint, float> GetCircleCollider2DRadiusIcall;
    internal static unsafe delegate*<uint, float, void> SetCircleCollider2DRadiusIcall;
    internal static unsafe delegate*<uint, float> GetCircleCollider2DDensityIcall;
    internal static unsafe delegate*<uint, float, void> SetCircleCollider2DDensityIcall;
    internal static unsafe delegate*<uint, float> GetCircleCollider2DFrictionIcall;
    internal static unsafe delegate*<uint, float, void> SetCircleCollider2DFrictionIcall;
    internal static unsafe delegate*<uint, float> GetCircleCollider2DRestitutionIcall;
    internal static unsafe delegate*<uint, float, void> SetCircleCollider2DRestitutionIcall;
    internal static unsafe delegate*<uint, bool> GetCircleCollider2DIsSensorIcall;
    internal static unsafe delegate*<uint, bool, void> SetCircleCollider2DIsSensorIcall;
    internal static unsafe delegate*<uint, ulong> GetCircleCollider2DCollisionLayerIcall;
    internal static unsafe delegate*<uint, ulong, void> SetCircleCollider2DCollisionLayerIcall;
    internal static unsafe delegate*<uint, ulong> GetCircleCollider2DCollisionMaskIcall;
    internal static unsafe delegate*<uint, ulong, void> SetCircleCollider2DCollisionMaskIcall;
    internal static unsafe delegate*<uint, bool> HasPolygonCollider2DComponentIcall;
    internal static unsafe delegate*<uint, Vector2> GetPolygonCollider2DOffsetIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetPolygonCollider2DOffsetIcall;
    internal static unsafe delegate*<uint, int> GetPolygonCollider2DPointCountIcall;
    internal static unsafe delegate*<uint, int, void> SetPolygonCollider2DPointCountIcall;
    internal static unsafe delegate*<uint, int, Vector2> GetPolygonCollider2DPointIcall;
    internal static unsafe delegate*<uint, int, Vector2, void> SetPolygonCollider2DPointIcall;
    internal static unsafe delegate*<uint, float> GetPolygonCollider2DDensityIcall;
    internal static unsafe delegate*<uint, float, void> SetPolygonCollider2DDensityIcall;
    internal static unsafe delegate*<uint, float> GetPolygonCollider2DFrictionIcall;
    internal static unsafe delegate*<uint, float, void> SetPolygonCollider2DFrictionIcall;
    internal static unsafe delegate*<uint, float> GetPolygonCollider2DRestitutionIcall;
    internal static unsafe delegate*<uint, float, void> SetPolygonCollider2DRestitutionIcall;
    internal static unsafe delegate*<uint, bool> GetPolygonCollider2DIsSensorIcall;
    internal static unsafe delegate*<uint, bool, void> SetPolygonCollider2DIsSensorIcall;
    internal static unsafe delegate*<uint, ulong> GetPolygonCollider2DCollisionLayerIcall;
    internal static unsafe delegate*<uint, ulong, void> SetPolygonCollider2DCollisionLayerIcall;
    internal static unsafe delegate*<uint, ulong> GetPolygonCollider2DCollisionMaskIcall;
    internal static unsafe delegate*<uint, ulong, void> SetPolygonCollider2DCollisionMaskIcall;
    internal static unsafe delegate*<uint, bool> HasEdgeCollider2DComponentIcall;
    internal static unsafe delegate*<uint, Vector2> GetEdgeCollider2DOffsetIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetEdgeCollider2DOffsetIcall;
    internal static unsafe delegate*<uint, Vector2> GetEdgeCollider2DPointAIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetEdgeCollider2DPointAIcall;
    internal static unsafe delegate*<uint, Vector2> GetEdgeCollider2DPointBIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetEdgeCollider2DPointBIcall;
    internal static unsafe delegate*<uint, float> GetEdgeCollider2DFrictionIcall;
    internal static unsafe delegate*<uint, float, void> SetEdgeCollider2DFrictionIcall;
    internal static unsafe delegate*<uint, float> GetEdgeCollider2DRestitutionIcall;
    internal static unsafe delegate*<uint, float, void> SetEdgeCollider2DRestitutionIcall;
    internal static unsafe delegate*<uint, bool> GetEdgeCollider2DIsSensorIcall;
    internal static unsafe delegate*<uint, bool, void> SetEdgeCollider2DIsSensorIcall;
    internal static unsafe delegate*<uint, ulong> GetEdgeCollider2DCollisionLayerIcall;
    internal static unsafe delegate*<uint, ulong, void> SetEdgeCollider2DCollisionLayerIcall;
    internal static unsafe delegate*<uint, ulong> GetEdgeCollider2DCollisionMaskIcall;
    internal static unsafe delegate*<uint, ulong, void> SetEdgeCollider2DCollisionMaskIcall;
    internal static unsafe delegate*<uint, bool> HasCapsuleCollider2DComponentIcall;
    internal static unsafe delegate*<uint, Vector2> GetCapsuleCollider2DOffsetIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetCapsuleCollider2DOffsetIcall;
    internal static unsafe delegate*<uint, Vector2> GetCapsuleCollider2DSizeIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetCapsuleCollider2DSizeIcall;
    internal static unsafe delegate*<uint, int> GetCapsuleCollider2DDirectionIcall;
    internal static unsafe delegate*<uint, int, void> SetCapsuleCollider2DDirectionIcall;
    internal static unsafe delegate*<uint, float> GetCapsuleCollider2DDensityIcall;
    internal static unsafe delegate*<uint, float, void> SetCapsuleCollider2DDensityIcall;
    internal static unsafe delegate*<uint, float> GetCapsuleCollider2DFrictionIcall;
    internal static unsafe delegate*<uint, float, void> SetCapsuleCollider2DFrictionIcall;
    internal static unsafe delegate*<uint, float> GetCapsuleCollider2DRestitutionIcall;
    internal static unsafe delegate*<uint, float, void> SetCapsuleCollider2DRestitutionIcall;
    internal static unsafe delegate*<uint, bool> GetCapsuleCollider2DIsSensorIcall;
    internal static unsafe delegate*<uint, bool, void> SetCapsuleCollider2DIsSensorIcall;
    internal static unsafe delegate*<uint, ulong> GetCapsuleCollider2DCollisionLayerIcall;
    internal static unsafe delegate*<uint, ulong, void> SetCapsuleCollider2DCollisionLayerIcall;
    internal static unsafe delegate*<uint, ulong> GetCapsuleCollider2DCollisionMaskIcall;
    internal static unsafe delegate*<uint, ulong, void> SetCapsuleCollider2DCollisionMaskIcall;
    internal static unsafe delegate*<uint, bool> HasJoint2DComponentIcall;
    internal static unsafe delegate*<uint, int> GetJoint2DTypeIcall;
    internal static unsafe delegate*<uint, int, void> SetJoint2DTypeIcall;
    internal static unsafe delegate*<uint, uint> GetJoint2DConnectedEntityIcall;
    internal static unsafe delegate*<uint, uint, void> SetJoint2DConnectedEntityIcall;
    internal static unsafe delegate*<uint, bool> GetJoint2DCollideConnectedIcall;
    internal static unsafe delegate*<uint, bool, void> SetJoint2DCollideConnectedIcall;
    internal static unsafe delegate*<uint, Vector2> GetJoint2DAnchorAIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetJoint2DAnchorAIcall;
    internal static unsafe delegate*<uint, Vector2> GetJoint2DAnchorBIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetJoint2DAnchorBIcall;
    internal static unsafe delegate*<uint, Vector2> GetJoint2DAxisIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetJoint2DAxisIcall;
    internal static unsafe delegate*<uint, bool> GetJoint2DEnableLimitIcall;
    internal static unsafe delegate*<uint, bool, void> SetJoint2DEnableLimitIcall;
    internal static unsafe delegate*<uint, Vector2> GetJoint2DLimitsIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetJoint2DLimitsIcall;
    internal static unsafe delegate*<uint, bool> GetJoint2DEnableMotorIcall;
    internal static unsafe delegate*<uint, bool, void> SetJoint2DEnableMotorIcall;
    internal static unsafe delegate*<uint, float> GetJoint2DMotorSpeedIcall;
    internal static unsafe delegate*<uint, float, void> SetJoint2DMotorSpeedIcall;
    internal static unsafe delegate*<uint, float> GetJoint2DMaxMotorForceOrTorqueIcall;
    internal static unsafe delegate*<uint, float, void> SetJoint2DMaxMotorForceOrTorqueIcall;
    internal static unsafe delegate*<uint, bool> GetJoint2DEnableSpringIcall;
    internal static unsafe delegate*<uint, bool, void> SetJoint2DEnableSpringIcall;
    internal static unsafe delegate*<uint, float> GetJoint2DHertzIcall;
    internal static unsafe delegate*<uint, float, void> SetJoint2DHertzIcall;
    internal static unsafe delegate*<uint, float> GetJoint2DDampingRatioIcall;
    internal static unsafe delegate*<uint, float, void> SetJoint2DDampingRatioIcall;
    internal static unsafe delegate*<uint, bool> HasSpriteComponentIcall;
    internal static unsafe delegate*<uint, NativeString> GetSpriteTextureKeyIcall;
    internal static unsafe delegate*<uint, NativeString, void> SetSpriteTextureKeyIcall;
    internal static unsafe delegate*<uint, Vector4> GetSpriteColorIcall;
    internal static unsafe delegate*<uint, Vector4, void> SetSpriteColorIcall;
    internal static unsafe delegate*<uint, Vector2> GetSpriteTilingFactorIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetSpriteTilingFactorIcall;
    internal static unsafe delegate*<uint, int> GetSpriteRenderOrderIcall;
    internal static unsafe delegate*<uint, int, void> SetSpriteRenderOrderIcall;
    internal static unsafe delegate*<uint, bool> GetSpriteCastShadowsIcall;
    internal static unsafe delegate*<uint, bool, void> SetSpriteCastShadowsIcall;
    internal static unsafe delegate*<uint, bool> GetSpriteReceiveShadowsIcall;
    internal static unsafe delegate*<uint, bool, void> SetSpriteReceiveShadowsIcall;
    internal static unsafe delegate*<uint, int> GetSpriteSubSpriteIndexIcall;
    internal static unsafe delegate*<uint, int, void> SetSpriteSubSpriteIndexIcall;
    internal static unsafe delegate*<uint, Vector2> GetSpriteUvMinIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetSpriteUvMinIcall;
    internal static unsafe delegate*<uint, Vector2> GetSpriteUvMaxIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetSpriteUvMaxIcall;
    internal static unsafe delegate*<uint, bool> HasMaterialComponentIcall;
    internal static unsafe delegate*<uint, NativeString> GetMaterialKeyIcall;
    internal static unsafe delegate*<uint, NativeString, void> SetMaterialKeyIcall;
    internal static unsafe delegate*<uint, bool> HasCanvasComponentIcall;
    internal static unsafe delegate*<uint, int> GetCanvasRenderModeIcall;
    internal static unsafe delegate*<uint, int, void> SetCanvasRenderModeIcall;
    internal static unsafe delegate*<uint, int> GetCanvasSortOrderIcall;
    internal static unsafe delegate*<uint, int, void> SetCanvasSortOrderIcall;
    internal static unsafe delegate*<uint, Vector2> GetCanvasReferenceResolutionIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetCanvasReferenceResolutionIcall;
    internal static unsafe delegate*<uint, bool> HasRectTransformComponentIcall;
    internal static unsafe delegate*<uint, Vector2> GetRectTransformAnchorMinIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetRectTransformAnchorMinIcall;
    internal static unsafe delegate*<uint, Vector2> GetRectTransformAnchorMaxIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetRectTransformAnchorMaxIcall;
    internal static unsafe delegate*<uint, Vector2> GetRectTransformPivotIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetRectTransformPivotIcall;
    internal static unsafe delegate*<uint, Vector2> GetRectTransformSizeDeltaIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetRectTransformSizeDeltaIcall;
    internal static unsafe delegate*<uint, Vector2> GetRectTransformAnchoredPositionIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetRectTransformAnchoredPositionIcall;
    internal static unsafe delegate*<uint, bool> HasDirectionalLight2DComponentIcall;
    internal static unsafe delegate*<uint, bool> GetDirectionalLight2DEnabledIcall;
    internal static unsafe delegate*<uint, bool, void> SetDirectionalLight2DEnabledIcall;
    internal static unsafe delegate*<uint, Vector3> GetDirectionalLight2DColorIcall;
    internal static unsafe delegate*<uint, Vector3, void> SetDirectionalLight2DColorIcall;
    internal static unsafe delegate*<uint, float> GetDirectionalLight2DIntensityIcall;
    internal static unsafe delegate*<uint, float, void> SetDirectionalLight2DIntensityIcall;
    internal static unsafe delegate*<uint, bool> GetDirectionalLight2DUseEntityRotationIcall;
    internal static unsafe delegate*<uint, bool, void> SetDirectionalLight2DUseEntityRotationIcall;
    internal static unsafe delegate*<uint, Vector2> GetDirectionalLight2DDirectionIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetDirectionalLight2DDirectionIcall;
    internal static unsafe delegate*<uint, bool> GetDirectionalLight2DCastShadowsIcall;
    internal static unsafe delegate*<uint, bool, void> SetDirectionalLight2DCastShadowsIcall;
    internal static unsafe delegate*<uint, float> GetDirectionalLight2DShadowStrengthIcall;
    internal static unsafe delegate*<uint, float, void> SetDirectionalLight2DShadowStrengthIcall;
    internal static unsafe delegate*<uint, float> GetDirectionalLight2DShadowSoftnessIcall;
    internal static unsafe delegate*<uint, float, void> SetDirectionalLight2DShadowSoftnessIcall;
    internal static unsafe delegate*<uint, int> GetDirectionalLight2DShadowSamplesIcall;
    internal static unsafe delegate*<uint, int, void> SetDirectionalLight2DShadowSamplesIcall;
    internal static unsafe delegate*<uint, float> GetDirectionalLight2DShadowDistanceIcall;
    internal static unsafe delegate*<uint, float, void> SetDirectionalLight2DShadowDistanceIcall;
    internal static unsafe delegate*<uint, float> GetDirectionalLight2DShadowBiasIcall;
    internal static unsafe delegate*<uint, float, void> SetDirectionalLight2DShadowBiasIcall;
    internal static unsafe delegate*<uint, bool> HasPointLight2DComponentIcall;
    internal static unsafe delegate*<uint, bool> GetPointLight2DEnabledIcall;
    internal static unsafe delegate*<uint, bool, void> SetPointLight2DEnabledIcall;
    internal static unsafe delegate*<uint, Vector3> GetPointLight2DColorIcall;
    internal static unsafe delegate*<uint, Vector3, void> SetPointLight2DColorIcall;
    internal static unsafe delegate*<uint, float> GetPointLight2DIntensityIcall;
    internal static unsafe delegate*<uint, float, void> SetPointLight2DIntensityIcall;
    internal static unsafe delegate*<uint, float> GetPointLight2DRadiusIcall;
    internal static unsafe delegate*<uint, float, void> SetPointLight2DRadiusIcall;
    internal static unsafe delegate*<uint, float> GetPointLight2DFalloffIcall;
    internal static unsafe delegate*<uint, float, void> SetPointLight2DFalloffIcall;
    internal static unsafe delegate*<uint, bool> GetPointLight2DCastShadowsIcall;
    internal static unsafe delegate*<uint, bool, void> SetPointLight2DCastShadowsIcall;
    internal static unsafe delegate*<uint, float> GetPointLight2DShadowStrengthIcall;
    internal static unsafe delegate*<uint, float, void> SetPointLight2DShadowStrengthIcall;
    internal static unsafe delegate*<uint, float> GetPointLight2DShadowSoftnessIcall;
    internal static unsafe delegate*<uint, float, void> SetPointLight2DShadowSoftnessIcall;
    internal static unsafe delegate*<uint, int> GetPointLight2DShadowSamplesIcall;
    internal static unsafe delegate*<uint, int, void> SetPointLight2DShadowSamplesIcall;
    internal static unsafe delegate*<uint, float> GetPointLight2DShadowBiasIcall;
    internal static unsafe delegate*<uint, float, void> SetPointLight2DShadowBiasIcall;
    internal static unsafe delegate*<uint, bool> HasUIImageComponentIcall;
    internal static unsafe delegate*<uint, bool> GetUIImageRaycastTargetIcall;
    internal static unsafe delegate*<uint, bool, void> SetUIImageRaycastTargetIcall;
    internal static unsafe delegate*<uint, bool> HasUIPanelComponentIcall;
    internal static unsafe delegate*<uint, Vector4> GetUIPanelBackgroundColorIcall;
    internal static unsafe delegate*<uint, Vector4, void> SetUIPanelBackgroundColorIcall;
    internal static unsafe delegate*<uint, bool> GetUIPanelUseSpriteTextureIcall;
    internal static unsafe delegate*<uint, bool, void> SetUIPanelUseSpriteTextureIcall;
    internal static unsafe delegate*<uint, bool> GetUIPanelRaycastTargetIcall;
    internal static unsafe delegate*<uint, bool, void> SetUIPanelRaycastTargetIcall;
    internal static unsafe delegate*<uint, bool> HasUITextComponentIcall;
    internal static unsafe delegate*<uint, NativeString> GetUITextValueIcall;
    internal static unsafe delegate*<uint, NativeString, void> SetUITextValueIcall;
    internal static unsafe delegate*<uint, NativeString> GetUITextFontFilePathIcall;
    internal static unsafe delegate*<uint, NativeString, void> SetUITextFontFilePathIcall;
    internal static unsafe delegate*<uint, float> GetUITextFontSizeIcall;
    internal static unsafe delegate*<uint, float, void> SetUITextFontSizeIcall;
    internal static unsafe delegate*<uint, Vector4> GetUITextColorIcall;
    internal static unsafe delegate*<uint, Vector4, void> SetUITextColorIcall;
    internal static unsafe delegate*<uint, bool> GetUITextRaycastTargetIcall;
    internal static unsafe delegate*<uint, bool, void> SetUITextRaycastTargetIcall;
    internal static unsafe delegate*<uint, bool> HasUIButtonComponentIcall;
    internal static unsafe delegate*<uint, bool> GetUIButtonInteractableIcall;
    internal static unsafe delegate*<uint, bool, void> SetUIButtonInteractableIcall;
    internal static unsafe delegate*<uint, bool> GetUIButtonUseStateColorsIcall;
    internal static unsafe delegate*<uint, bool, void> SetUIButtonUseStateColorsIcall;
    internal static unsafe delegate*<uint, Vector4> GetUIButtonNormalColorIcall;
    internal static unsafe delegate*<uint, Vector4, void> SetUIButtonNormalColorIcall;
    internal static unsafe delegate*<uint, Vector4> GetUIButtonHoveredColorIcall;
    internal static unsafe delegate*<uint, Vector4, void> SetUIButtonHoveredColorIcall;
    internal static unsafe delegate*<uint, Vector4> GetUIButtonPressedColorIcall;
    internal static unsafe delegate*<uint, Vector4, void> SetUIButtonPressedColorIcall;
    internal static unsafe delegate*<uint, Vector4> GetUIButtonDisabledColorIcall;
    internal static unsafe delegate*<uint, Vector4, void> SetUIButtonDisabledColorIcall;
    internal static unsafe delegate*<uint, bool> GetUIButtonIsHoveredIcall;
    internal static unsafe delegate*<uint, bool> GetUIButtonIsPressedIcall;
    internal static unsafe delegate*<uint, NativeString> GetUIButtonOnClickEventIcall;
    internal static unsafe delegate*<uint, NativeString, void> SetUIButtonOnClickEventIcall;
    internal static unsafe delegate*<uint, NativeString> GetUIButtonOnHoverEnterEventIcall;
    internal static unsafe delegate*<uint, NativeString, void> SetUIButtonOnHoverEnterEventIcall;
    internal static unsafe delegate*<uint, NativeString> GetUIButtonOnHoverExitEventIcall;
    internal static unsafe delegate*<uint, NativeString, void> SetUIButtonOnHoverExitEventIcall;
    internal static unsafe delegate*<uint, NativeString> GetUIButtonOnPressedEventIcall;
    internal static unsafe delegate*<uint, NativeString, void> SetUIButtonOnPressedEventIcall;
    internal static unsafe delegate*<uint, bool> HasUISliderComponentIcall;
    internal static unsafe delegate*<uint, bool> GetUISliderInteractableIcall;
    internal static unsafe delegate*<uint, bool, void> SetUISliderInteractableIcall;
    internal static unsafe delegate*<uint, float> GetUISliderMinValueIcall;
    internal static unsafe delegate*<uint, float, void> SetUISliderMinValueIcall;
    internal static unsafe delegate*<uint, float> GetUISliderMaxValueIcall;
    internal static unsafe delegate*<uint, float, void> SetUISliderMaxValueIcall;
    internal static unsafe delegate*<uint, float> GetUISliderValueIcall;
    internal static unsafe delegate*<uint, float, void> SetUISliderValueIcall;
    internal static unsafe delegate*<uint, Vector4> GetUISliderBackgroundColorIcall;
    internal static unsafe delegate*<uint, Vector4, void> SetUISliderBackgroundColorIcall;
    internal static unsafe delegate*<uint, Vector4> GetUISliderFillColorIcall;
    internal static unsafe delegate*<uint, Vector4, void> SetUISliderFillColorIcall;
    internal static unsafe delegate*<uint, Vector4> GetUISliderHandleColorIcall;
    internal static unsafe delegate*<uint, Vector4, void> SetUISliderHandleColorIcall;
    internal static unsafe delegate*<uint, float> GetUISliderHandleWidthIcall;
    internal static unsafe delegate*<uint, float, void> SetUISliderHandleWidthIcall;
    internal static unsafe delegate*<uint, float> GetUISliderHandleHeightMultiplierIcall;
    internal static unsafe delegate*<uint, float, void> SetUISliderHandleHeightMultiplierIcall;
    internal static unsafe delegate*<uint, bool> GetUISliderShowHandleIcall;
    internal static unsafe delegate*<uint, bool, void> SetUISliderShowHandleIcall;
    internal static unsafe delegate*<uint, bool> GetUISliderRuntimeDraggingIcall;
    internal static unsafe delegate*<uint, NativeString> GetUISliderOnValueChangedEventIcall;
    internal static unsafe delegate*<uint, NativeString, void> SetUISliderOnValueChangedEventIcall;
    internal static unsafe delegate*<uint, bool> HasAudioListener2DComponentIcall;
    internal static unsafe delegate*<uint, bool> GetAudioListener2DEnabledIcall;
    internal static unsafe delegate*<uint, bool, void> SetAudioListener2DEnabledIcall;
    internal static unsafe delegate*<uint, bool> GetAudioListener2DUsePrimaryCameraPositionIcall;
    internal static unsafe delegate*<uint, bool, void> SetAudioListener2DUsePrimaryCameraPositionIcall;
    internal static unsafe delegate*<uint, bool> HasAudioListener3DComponentIcall;
    internal static unsafe delegate*<uint, bool> GetAudioListener3DEnabledIcall;
    internal static unsafe delegate*<uint, bool, void> SetAudioListener3DEnabledIcall;
    internal static unsafe delegate*<uint, bool> GetAudioListener3DUsePrimaryCameraTransformIcall;
    internal static unsafe delegate*<uint, bool, void> SetAudioListener3DUsePrimaryCameraTransformIcall;
    internal static unsafe delegate*<uint, bool> HasAudioSourceComponentIcall;
    internal static unsafe delegate*<uint, NativeString> GetAudioSourceClipKeyIcall;
    internal static unsafe delegate*<uint, NativeString, void> SetAudioSourceClipKeyIcall;
    internal static unsafe delegate*<uint, float> GetAudioSourceVolumeIcall;
    internal static unsafe delegate*<uint, float, void> SetAudioSourceVolumeIcall;
    internal static unsafe delegate*<uint, float> GetAudioSourcePitchIcall;
    internal static unsafe delegate*<uint, float, void> SetAudioSourcePitchIcall;
    internal static unsafe delegate*<uint, bool> GetAudioSourcePlayOnStartIcall;
    internal static unsafe delegate*<uint, bool, void> SetAudioSourcePlayOnStartIcall;
    internal static unsafe delegate*<uint, bool> GetAudioSourceLoopIcall;
    internal static unsafe delegate*<uint, bool, void> SetAudioSourceLoopIcall;
    internal static unsafe delegate*<uint, bool> GetAudioSourceMutedIcall;
    internal static unsafe delegate*<uint, bool, void> SetAudioSourceMutedIcall;
    internal static unsafe delegate*<uint, int> GetAudioSourcePlaybackSpaceIcall;
    internal static unsafe delegate*<uint, int, void> SetAudioSourcePlaybackSpaceIcall;
    internal static unsafe delegate*<uint, NativeString> GetAudioSourceMixerGroupIcall;
    internal static unsafe delegate*<uint, NativeString, void> SetAudioSourceMixerGroupIcall;
    internal static unsafe delegate*<uint, float> GetAudioSourceSpatialMinDistanceIcall;
    internal static unsafe delegate*<uint, float, void> SetAudioSourceSpatialMinDistanceIcall;
    internal static unsafe delegate*<uint, float> GetAudioSourceSpatialMaxDistanceIcall;
    internal static unsafe delegate*<uint, float, void> SetAudioSourceSpatialMaxDistanceIcall;
    internal static unsafe delegate*<uint, float> GetAudioSourceSpatialRolloffExponentIcall;
    internal static unsafe delegate*<uint, float, void> SetAudioSourceSpatialRolloffExponentIcall;
    internal static unsafe delegate*<uint, float> GetAudioSourceStereoPanStrengthIcall;
    internal static unsafe delegate*<uint, float, void> SetAudioSourceStereoPanStrengthIcall;
    internal static unsafe delegate*<uint, int> GetAudioSourceSpatialRolloffModeIcall;
    internal static unsafe delegate*<uint, int, void> SetAudioSourceSpatialRolloffModeIcall;
    internal static unsafe delegate*<uint, float> GetAudioSourceDopplerFactorIcall;
    internal static unsafe delegate*<uint, float, void> SetAudioSourceDopplerFactorIcall;
    internal static unsafe delegate*<uint, bool> GetAudioSourceEnableDirectionalAttenuationIcall;
    internal static unsafe delegate*<uint, bool, void> SetAudioSourceEnableDirectionalAttenuationIcall;
    internal static unsafe delegate*<uint, float> GetAudioSourceDirectionalInnerAngleDegreesIcall;
    internal static unsafe delegate*<uint, float, void> SetAudioSourceDirectionalInnerAngleDegreesIcall;
    internal static unsafe delegate*<uint, float> GetAudioSourceDirectionalOuterAngleDegreesIcall;
    internal static unsafe delegate*<uint, float, void> SetAudioSourceDirectionalOuterAngleDegreesIcall;
    internal static unsafe delegate*<uint, float> GetAudioSourceDirectionalOuterVolumeIcall;
    internal static unsafe delegate*<uint, float, void> SetAudioSourceDirectionalOuterVolumeIcall;
    internal static unsafe delegate*<uint, NativeString> GetAudioSourceAttenuationCurveKeyIcall;
    internal static unsafe delegate*<uint, NativeString, void> SetAudioSourceAttenuationCurveKeyIcall;
    internal static unsafe delegate*<uint, bool> GetAudioSourceIsPlayingIcall;
    internal static unsafe delegate*<uint, bool> RequestAudioSourcePlayIcall;
    internal static unsafe delegate*<uint, void> StopAudioSourceIcall;
    internal static unsafe delegate*<uint, bool> HasAnimatorComponentIcall;
    internal static unsafe delegate*<uint, NativeString> GetAnimatorControllerKeyIcall;
    internal static unsafe delegate*<uint, NativeString, void> SetAnimatorControllerKeyIcall;
    internal static unsafe delegate*<uint, NativeString> GetAnimatorDefaultClipKeyIcall;
    internal static unsafe delegate*<uint, NativeString, void> SetAnimatorDefaultClipKeyIcall;
    internal static unsafe delegate*<uint, float> GetAnimatorPlaybackSpeedIcall;
    internal static unsafe delegate*<uint, float, void> SetAnimatorPlaybackSpeedIcall;
    internal static unsafe delegate*<uint, bool> GetAnimatorEnabledIcall;
    internal static unsafe delegate*<uint, bool, void> SetAnimatorEnabledIcall;
    internal static unsafe delegate*<uint, bool> GetAnimatorApplyToSpriteIcall;
    internal static unsafe delegate*<uint, bool, void> SetAnimatorApplyToSpriteIcall;
    internal static unsafe delegate*<uint, bool> GetAnimatorApplyToTransformIcall;
    internal static unsafe delegate*<uint, bool, void> SetAnimatorApplyToTransformIcall;
    internal static unsafe delegate*<uint, bool> GetAnimatorAutoPlayIcall;
    internal static unsafe delegate*<uint, bool, void> SetAnimatorAutoPlayIcall;
    internal static unsafe delegate*<uint, NativeString, bool, bool> PlayAnimatorStateIcall;
    internal static unsafe delegate*<uint, NativeString, bool, bool> PlayAnimatorClipIcall;
    internal static unsafe delegate*<uint, NativeString, bool, bool> SetAnimatorBoolParameterIcall;
    internal static unsafe delegate*<uint, NativeString, bool, bool> GetAnimatorBoolParameterIcall;
    internal static unsafe delegate*<uint, NativeString, float, bool> SetAnimatorFloatParameterIcall;
    internal static unsafe delegate*<uint, NativeString, float, float> GetAnimatorFloatParameterIcall;
    internal static unsafe delegate*<uint, NativeString, int, bool> SetAnimatorIntegerParameterIcall;
    internal static unsafe delegate*<uint, NativeString, int, int> GetAnimatorIntegerParameterIcall;
    internal static unsafe delegate*<uint, NativeString, bool> SetAnimatorTriggerParameterIcall;
    internal static unsafe delegate*<uint, NativeString, bool> ResetAnimatorTriggerParameterIcall;
    internal static unsafe delegate*<uint, NativeString> GetAnimatorCurrentStateNameIcall;
    internal static unsafe delegate*<uint, NativeString> GetAnimatorCurrentClipKeyIcall;
    internal static unsafe delegate*<uint, float> GetAnimatorStateTimeSecondsIcall;
    internal static unsafe delegate*<uint, float> GetAnimatorCurrentStateDurationSecondsIcall;
    internal static unsafe delegate*<uint, bool> HasAnimationEventReceiverComponentIcall;
    internal static unsafe delegate*<uint, bool> GetAnimationEventReceiverEnabledIcall;
    internal static unsafe delegate*<uint, bool, void> SetAnimationEventReceiverEnabledIcall;
    internal static unsafe delegate*<uint, int> GetAnimationEventReceiverDispatchedEventCountIcall;
    internal static unsafe delegate*<uint, int, NativeString> GetAnimationEventReceiverEventNameIcall;
    internal static unsafe delegate*<uint, int, NativeString> GetAnimationEventReceiverEventStringPayloadIcall;
    internal static unsafe delegate*<uint, int, float> GetAnimationEventReceiverEventFloatPayloadIcall;
    internal static unsafe delegate*<uint, int, int> GetAnimationEventReceiverEventIntegerPayloadIcall;
    internal static unsafe delegate*<uint, int, bool> GetAnimationEventReceiverEventBooleanPayloadIcall;
    internal static unsafe delegate*<uint, int, float> GetAnimationEventReceiverEventTimeSecondsIcall;
    internal static unsafe delegate*<uint, int, float> GetAnimationEventReceiverEventNormalizedTimeIcall;
    internal static unsafe delegate*<uint, bool> HasParticleEmitterComponentIcall;
    internal static unsafe delegate*<uint, float> GetParticleEmitterSpawnRateIcall;
    internal static unsafe delegate*<uint, float, void> SetParticleEmitterSpawnRateIcall;
    internal static unsafe delegate*<uint, float> GetParticleEmitterLifetimeMinIcall;
    internal static unsafe delegate*<uint, float, void> SetParticleEmitterLifetimeMinIcall;
    internal static unsafe delegate*<uint, float> GetParticleEmitterLifetimeMaxIcall;
    internal static unsafe delegate*<uint, float, void> SetParticleEmitterLifetimeMaxIcall;
    internal static unsafe delegate*<uint, bool> GetParticleEmitterLoopingIcall;
    internal static unsafe delegate*<uint, bool, void> SetParticleEmitterLoopingIcall;
    internal static unsafe delegate*<uint, float> GetParticleEmitterDurationIcall;
    internal static unsafe delegate*<uint, float, void> SetParticleEmitterDurationIcall;
    internal static unsafe delegate*<uint, bool> GetParticleEmitterPlayOnStartIcall;
    internal static unsafe delegate*<uint, bool, void> SetParticleEmitterPlayOnStartIcall;
    internal static unsafe delegate*<uint, bool> GetParticleEmitterBurstEnabledIcall;
    internal static unsafe delegate*<uint, bool, void> SetParticleEmitterBurstEnabledIcall;
    internal static unsafe delegate*<uint, int> GetParticleEmitterBurstCountIcall;
    internal static unsafe delegate*<uint, int, void> SetParticleEmitterBurstCountIcall;
    internal static unsafe delegate*<uint, Vector2> GetParticleEmitterSpawnOffsetMinIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetParticleEmitterSpawnOffsetMinIcall;
    internal static unsafe delegate*<uint, Vector2> GetParticleEmitterSpawnOffsetMaxIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetParticleEmitterSpawnOffsetMaxIcall;
    internal static unsafe delegate*<uint, bool> GetParticleEmitterUseRadialSpawnIcall;
    internal static unsafe delegate*<uint, bool, void> SetParticleEmitterUseRadialSpawnIcall;
    internal static unsafe delegate*<uint, float> GetParticleEmitterSpawnRadiusMinIcall;
    internal static unsafe delegate*<uint, float, void> SetParticleEmitterSpawnRadiusMinIcall;
    internal static unsafe delegate*<uint, float> GetParticleEmitterSpawnRadiusMaxIcall;
    internal static unsafe delegate*<uint, float, void> SetParticleEmitterSpawnRadiusMaxIcall;
    internal static unsafe delegate*<uint, float> GetParticleEmitterSpeedMinIcall;
    internal static unsafe delegate*<uint, float, void> SetParticleEmitterSpeedMinIcall;
    internal static unsafe delegate*<uint, float> GetParticleEmitterSpeedMaxIcall;
    internal static unsafe delegate*<uint, float, void> SetParticleEmitterSpeedMaxIcall;
    internal static unsafe delegate*<uint, float> GetParticleEmitterAngleMinIcall;
    internal static unsafe delegate*<uint, float, void> SetParticleEmitterAngleMinIcall;
    internal static unsafe delegate*<uint, float> GetParticleEmitterAngleMaxIcall;
    internal static unsafe delegate*<uint, float, void> SetParticleEmitterAngleMaxIcall;
    internal static unsafe delegate*<uint, bool> GetParticleEmitterRadialVelocityIcall;
    internal static unsafe delegate*<uint, bool, void> SetParticleEmitterRadialVelocityIcall;
    internal static unsafe delegate*<uint, float> GetParticleEmitterGravityModifierIcall;
    internal static unsafe delegate*<uint, float, void> SetParticleEmitterGravityModifierIcall;
    internal static unsafe delegate*<uint, float> GetParticleEmitterStartSizeMinIcall;
    internal static unsafe delegate*<uint, float, void> SetParticleEmitterStartSizeMinIcall;
    internal static unsafe delegate*<uint, float> GetParticleEmitterStartSizeMaxIcall;
    internal static unsafe delegate*<uint, float, void> SetParticleEmitterStartSizeMaxIcall;
    internal static unsafe delegate*<uint, float> GetParticleEmitterEndSizeIcall;
    internal static unsafe delegate*<uint, float, void> SetParticleEmitterEndSizeIcall;
    internal static unsafe delegate*<uint, Vector4> GetParticleEmitterStartColorIcall;
    internal static unsafe delegate*<uint, Vector4, void> SetParticleEmitterStartColorIcall;
    internal static unsafe delegate*<uint, Vector4> GetParticleEmitterEndColorIcall;
    internal static unsafe delegate*<uint, Vector4, void> SetParticleEmitterEndColorIcall;
    internal static unsafe delegate*<uint, float> GetParticleEmitterStartRotationMinIcall;
    internal static unsafe delegate*<uint, float, void> SetParticleEmitterStartRotationMinIcall;
    internal static unsafe delegate*<uint, float> GetParticleEmitterStartRotationMaxIcall;
    internal static unsafe delegate*<uint, float, void> SetParticleEmitterStartRotationMaxIcall;
    internal static unsafe delegate*<uint, float> GetParticleEmitterRotationSpeedMinIcall;
    internal static unsafe delegate*<uint, float, void> SetParticleEmitterRotationSpeedMinIcall;
    internal static unsafe delegate*<uint, float> GetParticleEmitterRotationSpeedMaxIcall;
    internal static unsafe delegate*<uint, float, void> SetParticleEmitterRotationSpeedMaxIcall;
    internal static unsafe delegate*<uint, NativeString> GetParticleEmitterTextureKeyIcall;
    internal static unsafe delegate*<uint, NativeString, void> SetParticleEmitterTextureKeyIcall;
    internal static unsafe delegate*<uint, int> GetParticleEmitterMaxParticlesIcall;
    internal static unsafe delegate*<uint, int, void> SetParticleEmitterMaxParticlesIcall;
    internal static unsafe delegate*<uint, bool> GetParticleEmitterIsPlayingIcall;
    internal static unsafe delegate*<uint, bool> GetParticleEmitterIsPausedIcall;
    internal static unsafe delegate*<uint, int> GetParticleEmitterAliveParticleCountIcall;
    internal static unsafe delegate*<uint, void> PlayParticleEmitterIcall;
    internal static unsafe delegate*<uint, bool, void> StopParticleEmitterIcall;
    internal static unsafe delegate*<uint, void> PauseParticleEmitterIcall;
    internal static unsafe delegate*<uint, void> ResumeParticleEmitterIcall;
    internal static unsafe delegate*<uint, int, void> EmitParticleEmitterIcall;
    internal static unsafe delegate*<uint, bool> HasGrid2DComponentIcall;
    internal static unsafe delegate*<uint, Vector2> GetGrid2DCellSizeIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetGrid2DCellSizeIcall;
    internal static unsafe delegate*<uint, Vector2> GetGrid2DCellGapIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetGrid2DCellGapIcall;
    internal static unsafe delegate*<uint, bool> HasTilemapLayerComponentIcall;
    internal static unsafe delegate*<uint, int> GetTilemapLayerGridWidthIcall;
    internal static unsafe delegate*<uint, int> GetTilemapLayerGridHeightIcall;
    internal static unsafe delegate*<uint, int, int, void> ResizeTilemapLayerGridIcall;
    internal static unsafe delegate*<uint, int> GetTilemapLayerRenderOrderIcall;
    internal static unsafe delegate*<uint, int, void> SetTilemapLayerRenderOrderIcall;
    internal static unsafe delegate*<uint, bool> GetTilemapLayerCollisionEnabledIcall;
    internal static unsafe delegate*<uint, bool, void> SetTilemapLayerCollisionEnabledIcall;
    internal static unsafe delegate*<uint, bool> GetTilemapLayerCastShadowsIcall;
    internal static unsafe delegate*<uint, bool, void> SetTilemapLayerCastShadowsIcall;
    internal static unsafe delegate*<uint, int> GetTilemapLayerCellCountIcall;
    internal static unsafe delegate*<uint, int, int, bool> IsTilemapLayerCellInBoundsIcall;
    internal static unsafe delegate*<uint, int, int, int> GetTilemapLayerTileIdIcall;
    internal static unsafe delegate*<uint, int, int, int, void> SetTilemapLayerTileIdIcall;
    internal static unsafe delegate*<uint, int, int, NativeString> GetTilemapLayerTileAssetKeyIcall;
    internal static unsafe delegate*<uint, int, int, NativeString, void> SetTilemapLayerTileAssetKeyIcall;
    internal static unsafe delegate*<uint, int> GetTilemapLayerTileTableEntryCountIcall;
    internal static unsafe delegate*<uint, int, NativeString> GetTilemapLayerTileTableEntryIcall;
    internal static unsafe delegate*<uint, int, NativeString, void> SetTilemapLayerTileTableEntryIcall;
    internal static unsafe delegate*<uint, NativeString, int> GetOrAddTilemapLayerTileTableEntryIcall;
    internal static unsafe delegate*<uint, bool> HasRigidbody2DComponentIcall;
    internal static unsafe delegate*<uint, int> GetRigidbody2DBodyTypeIcall;
    internal static unsafe delegate*<uint, int, void> SetRigidbody2DBodyTypeIcall;
    internal static unsafe delegate*<uint, bool> GetRigidbody2DFreezePositionXIcall;
    internal static unsafe delegate*<uint, bool, void> SetRigidbody2DFreezePositionXIcall;
    internal static unsafe delegate*<uint, bool> GetRigidbody2DFreezePositionYIcall;
    internal static unsafe delegate*<uint, bool, void> SetRigidbody2DFreezePositionYIcall;
    internal static unsafe delegate*<uint, bool> GetRigidbody2DFixedRotationIcall;
    internal static unsafe delegate*<uint, bool, void> SetRigidbody2DFixedRotationIcall;
    internal static unsafe delegate*<uint, bool> GetRigidbody2DUseCCDIcall;
    internal static unsafe delegate*<uint, bool, void> SetRigidbody2DUseCCDIcall;
    internal static unsafe delegate*<uint, bool> GetRigidbody2DEnableSleepIcall;
    internal static unsafe delegate*<uint, bool, void> SetRigidbody2DEnableSleepIcall;
    internal static unsafe delegate*<uint, bool> GetRigidbody2DStartAwakeIcall;
    internal static unsafe delegate*<uint, bool, void> SetRigidbody2DStartAwakeIcall;
    internal static unsafe delegate*<uint, bool> GetRigidbody2DInterpolateIcall;
    internal static unsafe delegate*<uint, bool, void> SetRigidbody2DInterpolateIcall;
    internal static unsafe delegate*<uint, bool> GetRigidbody2DHighContactQualityIcall;
    internal static unsafe delegate*<uint, bool, void> SetRigidbody2DHighContactQualityIcall;
    internal static unsafe delegate*<uint, int> GetRigidbody2DExtraSolverSubStepsIcall;
    internal static unsafe delegate*<uint, int, void> SetRigidbody2DExtraSolverSubStepsIcall;
    internal static unsafe delegate*<uint, float> GetRigidbody2DGravityScaleIcall;
    internal static unsafe delegate*<uint, float, void> SetRigidbody2DGravityScaleIcall;
    internal static unsafe delegate*<uint, float> GetRigidbody2DLinearDampingIcall;
    internal static unsafe delegate*<uint, float, void> SetRigidbody2DLinearDampingIcall;
    internal static unsafe delegate*<uint, float> GetRigidbody2DAngularDampingIcall;
    internal static unsafe delegate*<uint, float, void> SetRigidbody2DAngularDampingIcall;
    internal static unsafe delegate*<uint, Vector2> GetRigidbody2DLinearVelocityIcall;
    internal static unsafe delegate*<uint, Vector2, void> SetRigidbody2DLinearVelocityIcall;
    internal static unsafe delegate*<uint, float, void> SetRigidbody2DLinearVelocityXIcall;
    internal static unsafe delegate*<uint, float, void> SetRigidbody2DLinearVelocityYIcall;
    internal static unsafe delegate*<uint, Vector2, void> AddRigidbody2DLinearVelocityIcall;
    internal static unsafe delegate*<uint, bool, int> GetRigidbody2DContactCountIcall;
    internal static unsafe delegate*<uint, uint, bool, bool> HasContactWithEntityIcall;
    internal static unsafe delegate*<uint, bool, uint> GetContactEntityCountIcall;
    internal static unsafe delegate*<uint, bool, uint, uint> GetContactEntityAtIcall;
    internal static unsafe delegate*<Vector2, Vector2, float, ulong, RaycastHit2D> Raycast2DIcall;
#pragma warning restore 0649
}
