name: Test Linux Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-linux:
    name: Test Linux Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential g++ make cmake pkg-config
        sudo apt-get install -y libasound2-dev libpulse-dev libaudio-dev libjack-dev
        sudo apt-get install -y libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev libxxf86vm-dev libxss-dev
        sudo apt-get install -y libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev
        sudo apt-get install -y libdbus-1-dev libudev-dev libibus-1.0-dev
        sudo apt-get install -y libdrm-dev libgbm-dev
        sudo apt-get install -y libwayland-dev libxkbcommon-dev
        
    - name: Build SDL3 from source
      run: |
        echo "Building SDL3 from source..."
        cd /tmp
        git clone https://github.com/libsdl-org/SDL.git
        cd SDL
        git checkout release-3.2.18
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DSDL_STATIC=ON -DSDL_SHARED=OFF -DSDL_TEST=OFF
        make -j$(nproc)
        sudo make install
        sudo ldconfig
        
        echo "SDL3 installation info:"
        pkg-config --modversion sdl3 || echo "SDL3 not found by pkg-config"
        ls -la /usr/local/lib/libSDL3*
        ls -la /usr/local/include/SDL3/
        
    - name: Download premake5
      run: |
        echo "Downloading premake5..."
        curl -L -o premake5.tar.gz https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz
        tar -xzf premake5.tar.gz
        chmod +x premake5
        echo "Premake5 binary info:"
        ls -la premake5
        file premake5
        echo "Testing premake5 execution:"
        ./premake5 --version
        
        echo "Trying alternative premake5 version if current fails..."
        if ! ./premake5 gmake2 >/dev/null 2>&1; then
          echo "Current version failed, trying stable release..."
          curl -L -o premake5-stable.tar.gz https://github.com/premake/premake-core/releases/download/v5.0.0-alpha16/premake-5.0.0-alpha16-linux.tar.gz
          tar -xzf premake5-stable.tar.gz
          chmod +x premake5
          echo "New premake5 version:"
          ./premake5 --version
        fi
        
    - name: Generate Makefiles
      run: |
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "Checking if premake5.lua exists:"
        if [ -f "premake5.lua" ]; then
          echo "premake5.lua found"
          echo "premake5.lua contents:"
          cat premake5.lua
          echo "Checking sub-project premake5.lua files:"
          for file in */premake5.lua; do
            if [ -f "$file" ]; then
              echo "Found: $file"
            else
              echo "Missing: $file"
            fi
          done
        else
          echo "premake5.lua not found!"
          exit 1
        fi
        echo "Generating Makefiles..."
        echo "Premake5 workspace info:"
        ./premake5 --version
        echo "Available premake5 actions:"
        ./premake5 --help
        echo "Testing premake5 with a simple action:"
        ./premake5 clean || echo "Clean action failed (this is normal if no build files exist)"
        echo "Generating Makefiles..."
        echo "Running premake5 with verbose output:"
        set -e  # Exit on any error
        echo "Command: ./premake5 --verbose gmake2"
        ./premake5 --verbose gmake2
        echo "Premake5 exit code: $?"
        
        if [ $? -ne 0 ]; then
          echo "Premake5 failed with exit code $?"
          echo "Trying without verbose flag:"
          echo "Command: ./premake5 gmake2"
          ./premake5 gmake2
          echo "Premake5 exit code: $?"
          
          if [ $? -ne 0 ]; then
            echo "Premake5 failed again with exit code $?"
            echo "Trying gmake action (older version):"
            echo "Command: ./premake5 gmake"
            ./premake5 gmake
            echo "Premake5 exit code: $?"
            
            if [ $? -ne 0 ]; then
              echo "All premake5 actions failed"
              echo "Trying to list available actions:"
              ./premake5 --help | grep -A 20 "ACTIONS"
              exit 1
            fi
          fi
        fi
        echo "Generated files:"
        ls -la
        echo "Makefile targets (first 100 lines):"
        head -100 Makefile | grep -E "^[a-zA-Z]" || echo "No targets found in first 100 lines"
        echo "Available configurations:"
        grep -E "^[a-zA-Z][a-zA-Z0-9_-]*:" Makefile | head -20 || echo "No configurations found"
        echo "Looking for specific configuration patterns:"
        grep -i "debug" Makefile | head -10 || echo "No debug configurations found"
        grep -i "release" Makefile | head -10 || echo "No release configurations found"
        echo "All make targets (configurations):"
        make -qp | grep -E "^[a-zA-Z][a-zA-Z0-9_-]*:" | grep -v "^Makefile:" | head -30 || echo "No targets found"
        echo "Full Makefile content for debugging:"
        cat Makefile
        
    - name: Build project
      run: |
        echo "Building with verbose output..."
        echo "Available configurations from premake5.lua: Debug, Release, Dist"
        echo "Available platforms from premake5.lua: x64, ARM64"
        echo "Trying Debug-linux-x64 configuration..."
        make -j$(nproc) config=Debug-linux-x64 VERBOSE=1
        
        echo "Build exit code: $?"
        if [ $? -ne 0 ]; then
          echo "Build failed with exit code $?"
          echo "Trying alternative configuration format..."
          make -j$(nproc) config=Debug_x64 VERBOSE=1
          if [ $? -ne 0 ]; then
            echo "Alternative format also failed, trying Debug configuration only..."
            make -j$(nproc) config=Debug VERBOSE=1
            if [ $? -ne 0 ]; then
              echo "All build attempts failed"
              exit 1
            fi
          fi
        fi
        
    - name: List build output
      run: |
        echo "Build directory contents:"
        ls -la Build/ || echo "Build directory not found"
        echo "Looking for debug directories:"
        find Build/ -name "*debug*" -type d 2>/dev/null || echo "No debug directories found"
        echo "Looking for Debug directories:"
        find Build/ -name "*Debug*" -type d 2>/dev/null || echo "No Debug directories found"
        echo "Searching for all executables:"
        find Build/ -name "Test" -o -name "Sandbox" -o -name "*.exe" 2>/dev/null || echo "No executables found"
        
    - name: Run tests
      run: |
        # Try to find the test executable
        TEST_EXE=$(find Build/ -name "Test" -type f 2>/dev/null | head -1)
        if [ -n "$TEST_EXE" ]; then
          echo "Found test executable: $TEST_EXE"
          "$TEST_EXE" --success
        else
          echo "Test executable not found"
          find Build/ -name "*Test*" -type f 2>/dev/null || echo "No test files found"
        fi 