name: Test macOS Build

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  test-macos:
    name: Test macOS Build
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install SDL3
      run: |
        brew install sdl3
        echo "SDL3 installation info:"
        brew list sdl3
        echo "SDL3 library locations:"
        find /opt/homebrew -name "*SDL3*" 2>/dev/null || echo "No SDL3 found in /opt/homebrew"
        find /usr/local -name "*SDL3*" 2>/dev/null || echo "No SDL3 found in /usr/local"
        
    - name: Download premake5
      run: |
        curl -L -o premake5.tar.gz https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-macosx.tar.gz
        tar -xzf premake5.tar.gz
        chmod +x premake5
        
    - name: Generate Makefiles
      run: |
        ./premake5 gmake2
        echo "Generated files:"
        ls -la
        echo "Makefile targets (first 100 lines):"
        head -100 Makefile | grep -E "^[a-zA-Z]" || echo "No targets found in first 100 lines"
        echo "Available configurations:"
        grep -E "^[a-zA-Z][a-zA-Z0-9_-]*:" Makefile | head -20 || echo "No configurations found"
        
    - name: Build project
      run: |
        echo "Building with verbose output to see linker command:"
        make -j$(sysctl -n hw.ncpu) config=debug_arm64 VERBOSE=1
        
    - name: List build output
      run: |
        echo "Build directory contents:"
        ls -la Build/ || echo "Build directory not found"
        echo "Looking for ARM64 build output:"
        ls -la Build/debug_arm64-macosx-ARM64/ || echo "ARM64 build directory not found"
        echo "Looking for x64 build output:"
        ls -la Build/debug_x64-macosx-x64/ || echo "x64 build directory not found"
        
    - name: Run tests
      run: |
        # Try to find the test executable in ARM64 build
        TEST_EXE=$(find Build/debug_arm64-macosx-ARM64/ -name "Test" -type f 2>/dev/null | head -1)
        if [ -n "$TEST_EXE" ]; then
          echo "Found test executable: $TEST_EXE"
          "$TEST_EXE" --success
        else
          echo "Test executable not found in ARM64 build"
          find Build/debug_arm64-macosx-ARM64/ -name "*Test*" -type f 2>/dev/null || echo "No test files found in ARM64 build"
        fi 