name: Test macOS Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-macos:
    name: Test macOS Build
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install SDL3
      run: |
        brew install sdl3
        echo "SDL3 installation info:"
        brew list sdl3
        
    - name: Download premake5
      run: |
        echo "Downloading premake5..."
        curl -L -o premake5.tar.gz https://github.com/premake/premake-core/releases/download/v5.0.0-alpha16/premake-5.0.0-alpha16-macosx.tar.gz
        tar -xzf premake5.tar.gz
        chmod +x premake5
        
        echo "Premake5 version:"
        ./premake5 --version
        
    - name: Generate Makefiles
      run: |
        echo "Generating Makefiles..."
        ./premake5 gmake2
        
        if [ ! -f "Makefile" ]; then
          echo "Error: Makefile was not generated"
          exit 1
        fi
        
        echo "Makefile generated successfully"
        
    - name: Build ARM64
      run: |
        echo "Building ARM64 configuration..."
        make -j$(sysctl -n hw.ncpu) config=debug_arm64
        
        if [ $? -ne 0 ]; then
          echo "Error: ARM64 build failed"
          exit 1
        fi
        
        echo "ARM64 build completed successfully!"
        
    - name: Build x64
      run: |
        echo "Building x64 configuration..."
        make -j$(sysctl -n hw.ncpu) config=debug_x64
        
        if [ $? -ne 0 ]; then
          echo "Error: x64 build failed"
          exit 1
        fi
        
        echo "x64 build completed successfully!"
        
    - name: List build output
      run: |
        echo "Build directory contents:"
        ls -la Build/ || echo "Build directory not found"
        
        echo "ARM64 build output:"
        ls -la Build/debug_arm64-macosx-ARM64/ || echo "ARM64 build directory not found"
        
        echo "x64 build output:"
        ls -la Build/debug_x64-macosx-x64/ || echo "x64 build directory not found"
        
    - name: Run ARM64 tests
      run: |
        TEST_EXE=$(find Build/debug_arm64-macosx-ARM64/ -name "Test" -type f 2>/dev/null | head -1)
        if [ -n "$TEST_EXE" ]; then
          echo "Running ARM64 tests..."
          "$TEST_EXE" --success
          if [ $? -ne 0 ]; then
            echo "Warning: Some ARM64 tests failed"
          else
            echo "All ARM64 tests passed!"
          fi
        else
          echo "ARM64 test executable not found"
        fi
        
    - name: Run x64 tests
      run: |
        TEST_EXE=$(find Build/debug_x64-macosx-x64/ -name "Test" -type f 2>/dev/null | head -1)
        if [ -n "$TEST_EXE" ]; then
          echo "Running x64 tests..."
          "$TEST_EXE" --success
          if [ $? -ne 0 ]; then
            echo "Warning: Some x64 tests failed"
          else
            echo "All x64 tests passed!"
          fi
        else
          echo "x64 test executable not found"
        fi
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: macos-build-artifacts
        path: |
          Build/
          Makefile
        retention-days: 7 