name: Test macOS Build

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  test-macos:
    name: Test macOS Build
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download premake5
      run: |
        curl -L -o premake5.tar.gz https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-macosx.tar.gz
        tar -xzf premake5.tar.gz
        chmod +x premake5
        
    - name: Generate Makefiles
      run: |
        ./premake5 gmake2
        
    - name: Build project
      run: |
        make -j$(sysctl -n hw.ncpu) config=Debug
        
    - name: List build output
      run: |
        ls -la Build/Debug-macos-x64/
        
    - name: Run tests
      run: |
        ./Build/Debug-macos-x64/Test/Test --success 